# Project-wide Gradle settings.

# Asignar 6GB de RAM al Demonio Gradle y habilitar G1GC con Metaspace optimizado
org.gradle.jvmargs=-Xmx6144m -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# Memoria para el Demonio de Kotlin Compiler
kotlin.daemon.jvmargs=-Xmx2048m -XX:+UseG1GC

# Habilitar la ejecución de tareas en paralelo
org.gradle.parallel=true
org.gradle.tooling.parallel=true

# Activar el Build Cache de Gradle
org.gradle.caching=true

# Activar Configuration Cache para omitir la fase de configuración
org.gradle.configuration-cache=true

# Optimización de procesamiento incremental para KSP (Room y Hilt)
ksp.incremental=true
ksp.incremental.intermodule=true

# Compilación incremental de Kotlin
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true

# Clases R no transitivas para acelerar la generación de recursos
android.nonTransitiveAppRClass=true

# Estilo de código
kotlin.code.style=official
android.disallowKotlinSourceSets=false
